using System.ComponentModel.DataAnnotations;

namespace PurchasingService.Models;

public class OfferRequest
{
    [Required]
    public int SupplierId { get; set; }

    [Required]
    public string RequestId { get; set; } = string.Empty;

    [Required]
    public List<OfferRequestDetail> OfferDetails { get; set; } = new();

    [EmailAddress]
    public string? Email { get; set; }
}

public class OfferRequestDetail
{
    [Required]
    public string ProductName { get; set; } = string.Empty;

    [Range(1, int.MaxValue)]
    public int RequestedAmount { get; set; }
}

/// <summary>
/// Represents the response to an offer request.
/// </summary>
public class OfferResponse
{
    /// <summary>
    /// Autogenerated unique identifier for the offer response.
    /// </summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// The ID of the offer request.
    /// </summary>
    public string RequestId { get; set; } = string.Empty;

    /// <summary>
    /// The ID of the supplier.
    /// </summary>
    public int SupplierId { get; set; }

    /// <summary>
    /// The transportation cost for the offer.
    /// </summary>
    public decimal TransportationCost { get; set; }

    /// <summary>
    /// The timestamp when the offer was generated.
    /// </summary>
    public DateTimeOffset Timestamp { get; set; }

    /// <summary>
    /// The list of offer details included in the offer response.
    /// </summary>
    public IReadOnlyList<OfferResponseDetail> OfferDetails { get; set; } = Array.Empty<OfferResponseDetail>();

    /// <summary>
    /// Optional email recipient for the generated offer.
    /// </summary>
    public string? Email { get; set; }
}

public class OfferResponseDetail
{
    public string ProductName { get; set; } = string.Empty;

    public decimal BasePrice { get; set; }

    public decimal OfferedPrice { get; set; }

    public int RequestedAmount { get; set; }

    public int OfferedAmount { get; set; }

    public int DeliveryDurationDays { get; set; }

    public bool IsAvailable { get; set; }
}
